### ISSUE TITLE
Check if the Ubuntu Artful OVMF works with QEMU 2.10

### ISSUE THREAD

**Issue by saveriomiroddi** [saveriomiroddi/vga-passthrough#11]
See comment on #8 - artful version is `0~20170911.5dfba97c-1`

- [x] check if it can be proved via repo log [can't, conclusively]
- [x] live test
- [x] update documentation
- [x] also update the poor man's chapter title

**Comment by saveriomiroddi** [comment]
@schmitch yes, it works, confirmed on a live execution.

**Comment by schmitch** [comment]
Thanks! I'm hope that the rest of my hardware will work ;) When testing this weekend.

**Comment by saveriomiroddi** [comment]
Great! Please let me know the outcome, and the hardware. I don't have time to help with debugging, but it would be useful in general to add real-world examples in this guide.

**Comment by schmitch** [comment]
@saveriomiroddi actually my outcome is that I got it working.
However I needed to use Ubuntu 16.04 as the host since 17.10 does not boot with acpi on my ryzen 5 + asus b350m-a machine.
at the moment sound is choppy, however, I just use a emulated device.
The biggest problem was that I passed my boot GPU through which needed additional tweaks (nomodset + using a vbios romfile)
I might also move from plain qemu to libvirted and try out pulseaudio passtrough (which should work better than my GPU audio card or emulating audio)

**Comment by saveriomiroddi** [comment]
> I might also move from plain qemu to libvirted and try out pulseaudio passtrough (which should work better than my GPU audio card or emulating audio)

Audio choppiness is a well known QEMU issue. For 3€, it's possible to buy a USB audio card, which works perfectly :smile: 

> Edit: just my storage device is slowish. But that was expected.

This is unexpected, if you've installed the virtio drivers.

**Comment by schmitch** [comment]
Well I guess I need a new mainboard first. The boot loop probably comes from using the first graphics card as the primary boot. all the boot roms do not work and my mainboard is pratically garbadge, only 2x pcie 1x and 1x pcie 16x, whereas the other two 1x PCIe's are on the same IOMMU as the pci bridge. I probably buy some cheap AM4 sli board with double PCIE 16x

**Comment by schmitch** [comment]
nope as soon as any amd driver got installed it will bootloop till forever.
