### ISSUE TITLE
Easy CPU pinning

### ISSUE THREAD

**Issue by jukefr** [saveriomiroddi/vga-passthrough#25]
Pinning can be useful and is pretty easy to setup. Maybe add an easy way to implement it in the improvements section :

1. Take your number of cores and threads and divide that by 2. The host OS will use the first half and the guest the other half.
2. Edit your grub config with the 0-indexed numbers you came up with.
```
# For a CPU with 4 cores - 8 threads :
# thread 0,4 goes to host
# thread 1-3,5-7 goes to guest
GRUB_CMDLINE_LINUX_DEFAULT="... isolcpus=1-3,5-7 nohz_full=1-3,5-7 rcu_nocbs=1-3,5-7 ..."
```
3. `update-grub`
4. Use `chrt -r 1 taskset -c 1-3,5-7 qemu-system-x86_64 ...` to run qemu and have the load be round-robinned on threads 4 through 7.

**Comment by saveriomiroddi** [comment]
Hello!

I'm a bit reluctant about suggesting this strategy, because taking 50% off the CPU power from the host is a big hit, in especially, when considered in context.

If a particular load (we assume gaming) requires such extreme measures, it's likely that it also benefits from more cores (modern engines scale up to around 4 cores AFAIK), so this makes sense only for machines with 8+ cores (not threads) - on a 4 cores, such load would likely perform better on 4 unreserved cores, rather than 2 fully reserved.

Mostly, I wonder which audience would profit from this strategy. Do you use it on your machine? Did you benchmarked latency before and after? I'd be **very** interested in latency numbers, since people rarely mentions it.
